/datum/skills/covenant
	skills = list(
		SKILL_ENGINEER = SKILL_ENGINEER_TRAINED,
		SKILL_FIREMAN = SKILL_FIREMAN_DEFAULT,
		SKILL_CONSTRUCTION = SKILL_CONSTRUCTION_ENGI,
		SKILL_MEDICAL = SKILL_MEDICAL_TRAINED,
		SKILL_SURGERY = SKILL_SURGERY_DEFAULT,
		SKILL_CQC = SKILL_CQC_SKILLED,
		SKILL_LEADERSHIP = SKILL_LEAD_TRAINED,
		SKILL_OVERWATCH = SKILL_OVERWATCH_TRAINED,
		SKILL_JTAC = SKILL_JTAC_TRAINED,
		SKILL_MELEE_WEAPONS = SKILL_MELEE_TRAINED,
		SKILL_PILOT = SKILL_PILOT_TRAINED,
		SKILL_ENDURANCE = SKILL_ENDURANCE_TRAINED,
		SKILL_POLICE = SKILL_POLICE_FLASH,
	)

/datum/skills/covenant/sangheili
	name = "РљРѕРІРµРЅР°РЅС‚, СЃР°РЅРіС…РµР№Р»Рё"

	skills = list(
		SKILL_CQC = SKILL_CQC_MASTER,
		SKILL_MEDICAL = SKILL_MEDICAL_MEDIC,
		SKILL_LEADERSHIP = SKILL_LEAD_EXPERT,
		SKILL_JTAC = SKILL_JTAC_EXPERT,
		SKILL_MELEE_WEAPONS = SKILL_MELEE_TRAINED,
		SKILL_PILOT = SKILL_PILOT_EXPERT,
		SKILL_ENDURANCE = SKILL_ENDURANCE_MASTER,
		SKILL_POLICE = SKILL_POLICE_SKILLED,
	)

/datum/skills/covenant/unggoy
	name = "РљРѕРІРµРЅР°РЅС‚, СѓРЅРіРіРѕР№"

/datum/skills/covenant/ruuhtian
	name = "Covenant, Ruuhtian"
